app/views/home.py
import json
import random
import re
from datetime import date
from typing import List, Literal

from flask import Blueprint, make_response, redirect, render_template
from flask_login import current_user
from sqlalchemy import desc

from app import app, db
from app.models.news import News
from app.service import activity_service, company_service, privacy_service
from app.views.viewmodel.activity import ActivityViewModel
from app.views.viewmodel.jobs import JobsViewModel
from app.views.viewmodel.news import NewsViewModel

blueprint = Blueprint("home", __name__)


@blueprint.route("/", methods=["GET"])
def home():
    jobs = company_service.find_all_jobs(filter_inactive=True)

    random.seed(date.today())
    indices = [i for i in range(len(jobs))]
    random.shuffle(indices)
    jobs_view_models = [JobsViewModel(jobs[i]) for i in indices[:4]]

    activities = activity_service.get_activities_ending_after_now()

    activity_view_models = [ActivityViewModel(a, current_user) for a in activities[:4]]

    news: List[News] = (
        db.session.query(News)
        .filter(
            News.publish_date <= date.today(),
            db.or_(current_user.has_paid, db.not_(News.needs_paid)),
        )
        .order_by(desc(News.publish_date), desc(News.id))
        .limit(8)
        .all()
    )

    news_view_models = [NewsViewModel(n) for n in news]

    return render_template(
        "home/home.htm",
        activities=activity_view_models,
        title="Homepage",
        news=news_view_models,
        jobs=jobs_view_models,
    )


@blueprint.route("/privacy/policy/<any(nl,en):lang>/")
def privacy_policy(lang: Literal["en", "nl"]):
    policies = privacy_service.find_policies()
    if lang == "en":
        return redirect(policies.url_en)
    if lang == "nl":
        return redirect(policies.url_nl)


rule_parser = re.compile(r"<(.+?)>")
splitter = re.compile(r"<.+?>")


@blueprint.route("/jsglue.js")
def serve_js():
    """
    Based on https://github.com/stewartpark/Flask-JSGlue

    The code is inlined, because the pypi is not up-to-date and using the git version
    results in unknown template directories. This may be fixed after a new version
    is published and installable to site-package.
    """
    output = []
    for r in app.url_map.iter_rules():
        endpoint = r.endpoint
        if app.config["APPLICATION_ROOT"] == "/" or not app.config["APPLICATION_ROOT"]:
            rule = r.rule
        else:
            rule = "{root}{rule}".format(
                root=app.config["APPLICATION_ROOT"], rule=r.rule
            )
        rule_args = [x.split(":")[-1] for x in rule_parser.findall(rule)]
        rule_tr = splitter.split(rule)
        output.append((endpoint, rule_tr, rule_args))

    rules = sorted(output, key=lambda x: len(x[1]), reverse=True)

    return make_response(
        render_template("js_bridge.js", namespace="Flask", rules=json.dumps(rules)),
        200,
        {"Content-Type": "text/javascript"},
    )

app/views/news.py
from datetime import date

from flask import Blueprint, Response, abort, render_template
from flask_babel import lazy_gettext as _
from flask_login import current_user

from app import db
from app.decorators import require_role
from app.models.news import News
from app.roles import Roles
from app.service import news_service, role_service
from app.views.viewmodel.news import NewsViewModel

blueprint = Blueprint("news", __name__, url_prefix="/news")


# TODO Move page_nr to query parameter
# TODO https://gitlab.com/studieverenigingvia/viaduct/-/issues/872
@blueprint.route("/", methods=["GET"])
@blueprint.route("/<int:page_nr>/", methods=["GET"])
def root(page_nr=1):
    news_paginator = news_service.get_paginated_news(
        only_published=True, user=current_user, page=page_nr
    )

    news_items = [NewsViewModel(n) for n in news_paginator.items]

    can_write = role_service.user_has_role(current_user, Roles.NEWS_WRITE)
    return render_template(
        "news/list.htm",
        paginator=news_paginator,
        news_items=news_items,
        can_write=can_write,
    )


@blueprint.route("/create/", methods=["GET"])
@blueprint.route("/<news:news>/edit/", methods=["GET"])
@require_role(Roles.NEWS_WRITE)
def edit(news: News = None):
    if news:
        title = _("Edit news")
    else:
        title = _("Create news")
    return render_template("vue_content.htm", title=title)


@blueprint.route("/<news:news>/view/", methods=["GET"])
def view(news: News):
    if not news.can_read():
        return abort(403)

    can_write = role_service.user_has_role(current_user, Roles.NEWS_WRITE)

    return render_template("news/view_single.htm", news=news, can_write=can_write)


@blueprint.route("/rss/", methods=["GET"])
@blueprint.route("/rss/<string:locale>/")
def rss(locale="en"):
    title = "via nieuws" if locale == "nl" else "via news"
    items = (
        db.session.query(News)
        .filter(News.publish_date <= date.today(), db.or_(db.not_(News.needs_paid)))
        .order_by(News.publish_date.desc())
        .limit(20)
    )
    rv = render_template("news/rss.xml", title=title, news_items=items, locale=locale)
    return Response(rv, mimetype="application/atom+xml")

app/views/vue.py
from flask import Blueprint, render_template, redirect
from flask_babel import get_locale, gettext as _
from flask_login import login_required

from app.decorators import require_membership, require_role
from app.models.committee import Committee
from app.roles import Roles
from app.service import company_service
from app.views.file import send_picture

blueprint = Blueprint("vue", __name__)


@blueprint.route("/bug/report/")
@login_required
def bug_report():
    return public(title=_("Report a bug"))


@blueprint.route("/ereleden/", methods=["GET"])
@blueprint.route("/members-of-merit/", methods=["GET"])
def members_of_merit():
    return public(_("Members of merit"))


@blueprint.route("/jobs/", methods=["GET"])
def jobs():
    return public(_("Jobs"), "company-job-overview")


@blueprint.route("/companies/", methods=["GET"])
def companies():
    """Handle all public vue routes, defined in frontend/index.ts."""
    return public(_("Companies"), "company-overview")


def public(title, keep_alive_include=None):
    """Handle all public vue routes, defined in frontend/index.ts."""
    return render_template(
        "vue_content.htm", keep_alive_include=keep_alive_include, title=title
    )


@blueprint.route("/photos/", methods=["GET"], defaults=dict(title=_("Photos")))
@blueprint.route("/search/", methods=["GET"], defaults=dict(title=_("Search")))
@blueprint.route("/photos/<path:_>", methods=["GET"], defaults=dict(title=_("Photos")))
@require_membership
def membership(title, _=""):
    """Handle all member-only vue routes, defined in frontend/index.ts."""
    return render_template("vue_content.htm", title=title)


@blueprint.route("/jobs/<int:job_id>/", methods=["GET"])
def view(job_id):
    """Handle all company resource vue route, defined in frontend/index.ts."""
    job = company_service.get_job_by_id(job_id)
    title = job.title_en if get_locale() == "en" else job.title_nl
    return render_template(
        "vue_content.htm", keep_alive_include="company-overview", title=title
    )


@blueprint.route("/mailinglists/", methods=["GET"])
@blueprint.route("/mailinglists/<path:__>", methods=["GET"])
@require_role(Roles.MAILINGLIST_ADMIN)
def mailinglists(__=""):
    return render_template(
        "vue_content.htm",
        title=_("Mailinglists"),
        keep_alive_include="mailinglists-overview",
    )


@blueprint.route("/commissie/", methods=["GET"])
def committees():
    return render_template(
        "vue_content.htm",
        title=_("Committees"),
        keep_alive_include="committee-overview",
    )


@blueprint.route("/committee/picture/<committee:committee>/")
@blueprint.route("/committee/picture/<committee:committee>/<picture_type>/")
def committee_picture(committee: Committee, picture_type=None):
    if committee.picture_file_id is None:
        return redirect("/static/img/via_committee_default.jpg")

    return send_picture(
        committee.picture_file_id,
        f"committee_picture_{committee.en_name}",
        picture_type,
        thumbnail_size=(800, 600),
    )


@blueprint.route("/committee/create/", methods=["GET"])
@blueprint.route("/committee/<committee:committee>/edit/", methods=["GET"])
@require_role(Roles.GROUP_WRITE)
def committee_edit(committee=None):
    if committee:
        title = _("Edit committee")
    else:
        title = _("Create committee")
    return render_template(
        "vue_content.htm", title=title, keep_alive_include="committee-overview"
    )

app/templates/home/home.htm
{% extends 'base.htm' %}

{% block title %}{{ _('Study Association') }}{% endblock %}

{% block below_menu %}
    <div class="jumbotron" id="jumbotron" style="background-image: linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.6)), url('/static/img/jumbotron.jpeg');">
        <div class="container">
            <h1 class="display-4 font-weight-normal">{{_('Study Association')}} <strong>via</strong></h1>
            <p class="lead font-weight-normal">
                {{_("via, short for 'Vereniging Informatiewetenschappen Amsterdam' (Dutch), is the study association for Computer Science, Artificial Intelligence and Information Science at the University of Amsterdam.")}}
            </p>
        </div>
    </div>
{% endblock %}

{% block page %}
    <div class="row">
        <div class="col-md-7 newsrole">
            <a href="{{ url_for("news.root") }}">
                <h2>{{ _('Latest news') }}</h2>
            </a>
            {% for item in news %}
                <article>
                    <a href='{{ url_for('news.view', news=item) }}'>
                        <h3>{{ item.title }}</h3>
                    </a>
                    <div class="user">
                        <img class="avatar" src="{{ item.user_avatar }}">
                        <div class="meta">
                            <span class="author">{{ item.user_name }}</span>
                            <span class="date">{{ item.publish_date}}</span>
                        </div>
                    </div>
                    <div class="excerpt">
                        {{ item.content
                           | markdown_summary(300,
                                              truncate_method="paragraph",
                                              read_more=item.read_more) }}
                    </div>
                </article>
            {% endfor %}

            <a href="{{ url_for("news.root", page_nr=2) }}">
                <p>{{ _("View more news") }}</p>
            </a>

        </div>
        <div class="col-md-5">
            {% include 'activity/view_home.htm' %}
            {% include 'home/jobs_simple.htm' %}
        </div>
    </div> {# /.row #}
{% endblock %}

app/templates/home/jobs_simple.htm
<a href="{{ url_for('vue.jobs') }}">
    <h2>{{ _('Vacancies') }}</h2>
</a>

{% for job in jobs %}
<div class="job-simple">
    <div class="job-simple-left">
        <img src="{{ job.logo }}" alt="{{ job.company.name }}"/>
    </div>
    <div class="job-simple-right">
        <a href="{{ job.url }}">
            <h4> {{ job.title }} </h4>
        </a>
        <h6 class="text-muted">{{ job.company.name }}, {{ job.contract_of_service }}</h6>
        <p>
            {{ job.description | markdown_summary(140, truncate_method="paragraph") }}
        </p>
    </div>
</div>
{% endfor %}