app/models/activity.py
from datetime import datetime, timezone
from functools import cached_property
from typing import TYPE_CHECKING

import pytz
from babel.dates import format_timedelta
from flask import has_request_context
from flask_babel import lazy_gettext as _
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import backref, relationship

from app import constants, get_locale
from app.extensions import mapper_registry
from app.models.base_model import BaseEntity

if TYPE_CHECKING:
    from app.models.user import User  # noqa


@mapper_registry.mapped
class Activity(BaseEntity):
    __tablename__ = "activity"
    prints = ("id", "name", "start_time", "end_time")

    owner_id = Column(Integer, ForeignKey("user.id"))
    en_name: str = Column(String(256), nullable=False)
    en_description: str = Column(Text, nullable=False)
    nl_name: str = Column(String(256), nullable=False)
    nl_description: str = Column(Text, nullable=False)
    start_time: datetime = Column(DateTime(timezone=True), nullable=False)
    end_time: datetime = Column(DateTime(timezone=True), nullable=False)
    location: str = Column(String(1024), nullable=False)
    price: str = Column(String(16), nullable=False)
    picture_file_id = Column(Integer, ForeignKey("file.id"))

    google_event_id = Column(String(64))
    owner: "User" = relationship("User", backref=backref("activities", lazy="dynamic"))

    pretix_event_slug = Column(String(64))

    def __str__(self):
        if self.start_time.date() == self.end_time.date():
            end_time_fmt = constants.TIME_FORMAT
        else:
            end_time_fmt = constants.DT_FORMAT

        tz = pytz.timezone("Europe/Amsterdam")
        return "{} ({} - {})".format(
            self.name,
            self.start_time.astimezone(tz).strftime(constants.DT_FORMAT),
            self.end_time.astimezone(tz).strftime(end_time_fmt),
        )

    @property
    def is_pretix_event(self):
        return self.pretix_event_slug is not None

    def is_in_future(self):
        return datetime.now(timezone.utc) < self.start_time

    def is_in_past(self):
        return datetime.now(timezone.utc) >= self.end_time

    def get_timedelta_to_start(self):
        """Locale based description of time left to start."""
        now = datetime.now(timezone.utc)
        return format_timedelta(now - self.start_time, locale=get_locale())

    def get_timedelta_from_end(self):
        """Locale based description of time in the past."""
        now = datetime.now(timezone.utc)
        return format_timedelta(now - self.end_time, locale=get_locale())

    def get_timedelta_to_end(self):
        """Locale based description of time until the end of the activity."""
        now = datetime.now(timezone.utc)
        return format_timedelta(self.end_time - now, locale=get_locale())

    def till_now(self):
        """Locale based description of datetimedelta till now."""
        if self.is_in_future():
            return _("in") + " %s" % (self.get_timedelta_to_start())

        if self.is_in_past():
            return "%s " % (self.get_timedelta_from_end()) + _("ago")

        return _("still") + " %s" % (self.get_timedelta_to_end())

    @cached_property
    def name(self):
        locale = "en"
        if has_request_context():
            locale = get_locale()
        return self.get_localized_name_desc(locale)[0]

    @cached_property
    def description(self):
        locale = "en"
        if has_request_context():
            locale = get_locale()
        return self.get_localized_name_desc(locale)[1]

    def get_localized_name_desc(self, locale=None):
        if not locale:
            locale = get_locale()

        nl_available = self.nl_name and self.nl_description
        en_available = self.en_name and self.en_description
        if locale == "nl" and nl_available:
            name = self.nl_name
            description = self.nl_description
        elif locale == "en" and en_available:
            name = self.en_name
            description = self.en_description
        elif nl_available:
            name = self.nl_name + " (Dutch)"
            description = self.nl_description
        elif en_available:
            name = self.en_name + " (Engels)"
            description = self.en_description
        else:
            name = "N/A"
            description = "N/A"

        return name, description

app/views/activity.py
from datetime import datetime, timedelta
from urllib.parse import urljoin

from flask import (
    Blueprint,
    Response,
    abort,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_babel import gettext as _
from flask_login import current_user
from sqlalchemy import or_

from app import app, db
from app.decorators import require_role
from app.exceptions.base import BusinessRuleException
from app.models.activity import Activity
from app.roles import Roles
from app.service import activity_service, role_service
from app.utils.serialize_sqla import serialize_sqla
from app.views.file import send_picture
from app.views.viewmodel.activity import ActivityViewModel

blueprint = Blueprint("activity", __name__, url_prefix="/activities")


# Overview of activities
# TODO Move page parameter to query parameters.
@blueprint.route("/", methods=["GET"])
@blueprint.route("/<any(archive):archive>/", methods=["GET"])
@blueprint.route("/list/<int:page_nr>/", methods=["GET"])
@blueprint.route("/list/<any(archive):archive>/<int:page_nr>/", methods=["GET"])
def view(archive=None, page_nr=1):
    search = request.args.get("search", "")
    query = db.session.query(Activity)
    if archive == "archive":
        if current_user.is_anonymous:
            abort(403)
        query = query.filter(Activity.end_time < datetime.today())
        query = query.order_by(Activity.start_time.desc())
    else:
        query = query.order_by(Activity.start_time.asc())
        query = query.filter(Activity.end_time > (datetime.now() - timedelta(hours=12)))

    if search:
        search_key = "%{}%".format(search)
        query = query.filter(
            or_(Activity.en_name.ilike(search_key), Activity.nl_name.ilike(search_key))
        )

    can_write = role_service.user_has_role(current_user, Roles.ACTIVITY_WRITE)

    # TODO convert to page query parameter
    pagination = query.paginate(page_nr, 30, False)
    pagination.items = [ActivityViewModel(a, current_user) for a in pagination.items]

    return render_template(
        "activity/view.htm",
        activities=pagination,
        archive=archive,
        can_write=can_write,
        search=search,
    )


# TODO https://gitlab.com/studieverenigingvia/viaduct/-/issues/857
@blueprint.route("/<activity:activity>/remove/", methods=["POST"])
@require_role(Roles.ACTIVITY_WRITE)
def remove_activity(activity):
    try:
        activity_service.remove_activity(activity)
        flash(_("Activity has been removed successfully"))
    except BusinessRuleException:
        flash(
            _("Unable to delete activity: it is referenced by a newsletter"), "danger"
        )

    return redirect(url_for("activity.view"))


@blueprint.route("/<activity:activity>/", methods=["GET"])
def get_activity(activity: Activity):
    """Activity register and update endpoint.

    Register and update for an activity, with handling of custom forms
    and payment.
    """
    if activity.is_in_past() and current_user.is_anonymous:
        abort(403)

    if activity.is_in_past() and current_user.is_anonymous:
        abort(403)

    view_model = ActivityViewModel(activity, current_user)

    return view_model.render()


@blueprint.route("/create/", methods=["GET"])
@require_role(Roles.ACTIVITY_WRITE)
def create_pretix():
    title = _("Create activity")
    return render_template("vue_content.htm", title=title)


@blueprint.route("/<activity:activity>/pretix/", methods=["GET"])
def pretix_view(activity: Activity):
    if not activity.pretix_event_slug:
        abort(404)
    host = app.config["PRETIX_HOST"]
    organizer = app.config["PRETIX_ORGANIZER"]
    slug = activity.pretix_event_slug
    return redirect(urljoin(host, f"/control/event/{organizer}/{slug}/"))


@blueprint.route("/<activity:activity>/edit/", methods=["GET"])
@require_role(Roles.ACTIVITY_WRITE)
def edit(activity: Activity):
    title = _("Edit") + " " + str(activity.name)
    return render_template("vue_content.htm", title=title)


# TODO Word deze route door iets uberhaupt gebruikt?
@blueprint.route("/export/", methods=["GET"])
def export_activities():
    activities = (
        db.session.query(Activity)
        .filter(Activity.end_time > (datetime.now() - timedelta(hours=12)))
        .order_by(Activity.start_time.asc())
        .all()
    )
    return jsonify(data=serialize_sqla(activities))


@blueprint.route("/rss/", methods=["GET"])
@blueprint.route("/rss/<string:locale>/")
def rss(locale="en"):
    title = "via activiteiten" if locale == "nl" else "via activities"
    activities = (
        db.session.query(Activity)
        .filter(Activity.end_time > (datetime.now() - timedelta(hours=12)))
        .order_by(Activity.start_time.asc())
        .all()
    )

    rv = render_template(
        "activity/rss.xml", title=title, activities=activities, locale=locale
    )
    return Response(rv, mimetype="application/atom+xml")


@blueprint.route("/<activity:activity>/picture/")
@blueprint.route("/<activity:activity>/picture/<picture_type>/")
def picture(activity: Activity, picture_type=None):
    if activity.picture_file_id is None or (
        current_user.is_anonymous and activity.is_in_past()
    ):
        return redirect("/static/img/via_activity_default.png")

    return send_picture(
        activity.picture_file_id, f"activity_picture_{activity.name}", picture_type
    )

app/templates/activity/view.htm
{% extends "base.htm" %}

{% from "macros/pagination.htm" import render_pagination %}

{% block title %}
    {{  _('Activities') }} {% if archive %}{{ _('archive') }}{% endif %}
{% endblock %}

{% block page %}
<div class="row">
    <div class="col-md-12">
        <div class="btn-group">
            {% if can_write %}
                <a href="{{ url_for('activity.create_pretix') }}" class="btn btn-success">
                    <i class="fas fa-plus"></i>
                    {{ _('New activity') }}
                </a>
            {% endif %}

            {% if archive == 'archive' %}
                <a href="{{ url_for('activity.view') }}" class="btn btn-info">
                    {{ _('Show upcoming') }}
                </a>
            {% else %}
                <a href="{{ url_for('activity.view', archive='archive') }}"
                   class="btn btn-light">
                    {{ _('Show archive') }}
                </a>
            {% endif %}

            <a href="{{ config['EVENTS_CALENDAR_ADD_CALENDAR_URL'] }}"
               target="_blank" class="btn btn-primary">
                <i class="fab fa-google"></i>
                <span class="d-none d-sm-inline-block">{{ _('Add to Google Calendar') }}</span>
            </a>

            <a href="{{ config['EVENTS_CALENDAR_ICS_URL'] }}"
               target="_blank" class="btn btn-primary">
                <i class="far fa-calendar-alt"></i>
                <span class="d-none d-sm-inline-block">{{ _('iCal') }}</span>
            </a>

            <a href="{{ url_for('activity.rss', locale=get_locale()) }}"
               target="_blank" class="btn btn-primary">
                <i class="fas fa-rss"></i>
                <span class="d-none d-sm-inline-block">{{ _('RSS') }}</span>
            </a>

            <form action="{{ url_for('activity.view', archive=archive) }}" class="form-inline ml-auto">
                <div class="input-group">
                    <input name="search" id="search" class="form-control"
                           type="text"
                           placeholder="{{ _('Search activities') }}"
                           value="{{ search }}">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-search" id="submit"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br>

<div class="row">
    <div class="col-md-12">

    {% for activity in activities.items %}
        <div class="activity-card card mb-3">
            <a class="activity-picture" href="{{ activity.activity_url }}">
                <img class="card-img" alt="Activity thumbnail" src="{{ activity.picture_url }}">
            </a>
            <div>
                <div class="card-body pb-2 activity-content">
                    <div class="activity-title mb-2">
                        <h5 class="card-title mb-0"><a href="{{ activity.activity_url }}">{{ activity.title }}</a></h5>
                        {{ activity.formatted_time }} <small class="activity-time-relative text-muted">{{ activity.relative_time }}</small>
                    </div>

                    <div class="activity-text mb-2">
                        <div class="card-text">
                            {{ activity.description
                               | markdown_summary(600,
                                                 truncate_method="word",
                                                 read_more=" ...") }}
                        </div>
                    </div>

                    <div class="activity-details">
                        <p class="card-text">
                            <small class="text-muted">
                                {{ activity.formatted_price }} -
                                {% if activity.location_is_url %}
                                    <a href="{{ activity.location }}" target="_blank" rel="noopener" >
                                        {{ activity.location_name }}
                                    </a>
                                {% else %}
                                    <span>{{ activity.location_name }}</span>
                                {% endif %}
                            </small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <hr />
    {{ render_pagination(activities, 'activity.view', archive=archive, search=search) }}

    </div>
</div>
{% endblock %}

app/templates/activity/view_home.htm
<a href="/activities">
    <h2>{{_('Activity overview')}}</h2>
</a>

{% for activity in activities %}
    <div class="activity-simple">
        <div class="activity-header" >
            <div class="activity-thumbnail"></div>
            <h3>
                <a href="{{ activity.activity_url }}">{{ activity.title }}</a>
            </h3>
            <span class="activity-till-now small text-light">
                {{ activity.relative_time }}
            </span>
        </div>
        <div class="activity-simple-content">
            <ul class="list-unstyled">
                <li class="overflow-dots"><i class="far fa-calendar-alt"></i>
                    {{ activity.formatted_time }}</li>

                <li class="overflow-dots"><i class="fas fa-map-marker-alt"></i>
                    {{ activity.location_name }}</li>
            </ul>
            {{ activity.description
               | markdown_summary(400,
                                 truncate_method="word",
                                 read_more="...") }}
        </div>
    </div>
{% endfor %}

<p class="mb-5 small">
{{_('Do you have an idea for an activity?')}}<br>
{{_('Send an e-mail to the')}} <a href="mailto:actie@svia.nl">{{_('Activitycommittee')}}</a>.
</p>

app/templates/activity/view_single.htm
{% extends "content.htm" %}

{% from "macros/form.htm" import render_field, render_field_disabled, render_checkbox, render_submit %}

{% block og_image %}
<meta property="og:image" content="{{ url_for('activity.picture', _external=True, activity=view_model.activity, picture_type='thumbnail') }}" />
<meta property="og:image:alt" content="Activity thumbnail" />
<meta property="og:image:type" content="image/png" />
{% endblock %}

{% block includes %}
    <script type="application/ld+json">{{ view_model.json_ld_object | safe }}</script>
{% endblock %}

{% block post_main_include %}
    {% if view_model.is_pretix_event %}
        <link rel="stylesheet" type="text/css" href="{{ view_model.pretix_widget_url }}/widget/v1.css">
        <script type="text/javascript" src="https://pretix.svia.nl/widget/v1.{{ get_locale() }}.js" async></script>
    {% endif %}
{% endblock %}


{% block title %}{{ view_model.title }}{% endblock %}

{% block content %}
    {# Activity name and relative time #}
    <div class="pb-2 mt-4 mb-2 border-bottom">
        {% if view_model.can_write %}
            <a href="{{ url_for('activity.edit', activity=view_model.activity) }}"
               class="btn btn-warning float-right">
               <i class="far fa-edit"></i>
                {{ _('Edit') }}
            </a>
        {% endif %}

        <h1>{{ view_model.title }}</h1>
        <small> {{ view_model.relative_time }}</small>
    </div>

    <div class="row">
        {# Activity price, time, location, picture, description #}
        {# full column width if there is no activity picture, otherwise do a 8/4 split. #}
        <div class="{% if view_model.has_picture %}col-md-8{% else %}col-md-12{% endif %} col-xs-12">
            <div class="time">
                <i class="far fa-calendar-alt"></i> {{ view_model.formatted_time }}
            </div>

            {% if view_model.location %}
                <div class="location">
                    <i class="fas fa-map-marker"></i>
                    {% if view_model.location_is_url %}
                        <a href="{{ view_model.location }}" target="_blank" rel="noopener" >
                            {{ view_model.location_name }}
                        </a>
                    {% else %}
                        <span>{{ view_model.location_name }}</span>
                    {% endif %}
                </div>
            {% endif %}
            <p>
                <b>{{ view_model.formatted_price }}</b>
            </p>

            <hr class="activity-short-hr">

            <p>{{ view_model.description | markdown }}</p>
        </div>

        {# Activity picture #}
        {% if view_model.has_picture %}
            <div class="col-md-4 col-xs-12">
                <a class="activity-picture-link"
                   href="{{ url_for('activity.picture', activity=view_model.activity) }}">
                    <img class="activity-picture"
                         src="{{ url_for('activity.picture', activity=view_model.activity, picture_type='thumbnail') }}">
                </a>
                <br>
            </div>
        {% endif %}
    </div>
    <hr class="activity-short-hr">
    {% if view_model.user_registration_state == "login" %}
        <p>{{ _('You must be logged-in to register for an activity.') }}</p>
        <a href="{{ url_for('login.sign_in', next=url_for('activity.get_activity', activity=view_model.activity)) }}">
            {{ _('Sign in') }}
        </a>
    {% elif view_model.user_registration_state == "favourer_disallowed" %}
        <p class="alert alert-info">
            {{ _('You are not able to register for this event, as favourers (Vriend van VIA) are not invited to this event.') }}
        </p>
    {% elif view_model.user_registration_state == "membership" %}
        <p class="alert alert-info">
            {{ _('You need to have valid membership to register for this activity. For more information, visit the <a href="/lidmaatschap">membership page</a>') }}.
        </p>
    {% elif view_model.user_registration_state == "register" %}
        {% if view_model.pretix_order_code %}
            <div class="alert alert-info">
            {{ _("You already have an order for this event. You can view it ") }}
            <a href="{{ view_model.pretix_user_order_url }}" target="_blank">{{ _("here") }}</a>
            </div>
        {% else %}
        <pretix-widget
                event="{{ view_model.pretix_widget_url }}"
                {{ view_model.skip_ssl_check }}
                data-user-info-url="{{ view_model.pretix_user_info_url }}"
        ></pretix-widget>
        {% endif %}
    {% endif %}
{% endblock %}