app/models/news.py
import datetime
from datetime import date
from functools import cached_property
from typing import TYPE_CHECKING

from flask import has_request_context
from flask_login import current_user
from sqlalchemy import Boolean, Column, Date, Integer, String, Text
from sqlalchemy.orm import backref, relationship
from sqlalchemy.schema import ForeignKey

from app import get_locale
from app.extensions import mapper_registry
from app.models.base_model import BaseEntity

if TYPE_CHECKING:
    from app.models.user import User  # noqa


@mapper_registry.mapped
class News(BaseEntity):
    __tablename__ = "news"
    nl_title = Column(String(256), default="")
    en_title = Column(String(256), default="")
    nl_content = Column(Text, default="")
    en_content = Column(Text, default="")

    user_id = Column(Integer, ForeignKey("user.id"))
    user: "User" = relationship("User", backref=backref("news", lazy="dynamic"))
    needs_paid = Column(Boolean, default=False, nullable=False)

    publish_date = Column(Date, default=date.today)

    def __str__(self):
        return "{} ({})".format(self.title, self.publish_date)

    @property
    def modified_after_creation(self):
        return (self.modified - self.created) >= datetime.timedelta(seconds=1)

    def can_read(self, user=current_user):
        return not self.needs_paid or user.has_paid

    @cached_property
    def title(self):
        locale = "en"
        if has_request_context():
            locale = get_locale()
        return self.get_localized_title_content(locale)[0]

    @cached_property
    def content(self):
        locale = "en"
        if has_request_context():
            locale = get_locale()
        return self.get_localized_title_content(locale)[1]

    def get_localized_title_content(self, locale=None):
        if not locale:
            locale = get_locale()

        nl_available = self.nl_title and self.nl_content
        en_available = self.en_title and self.en_content
        if locale == "nl" and nl_available:
            title = self.nl_title
            content = self.nl_content
        elif locale == "en" and en_available:
            title = self.en_title
            content = self.en_content
        elif nl_available:
            title = self.nl_title + " (Dutch)"
            content = self.nl_content
        elif en_available:
            title = self.en_title + " (Engels)"
            content = self.en_content
        else:
            title = "N/A"
            content = "N/A"

        return title, content

app/views/home.py
import json
import random
import re
from datetime import date
from typing import List, Literal

from flask import Blueprint, make_response, redirect, render_template
from flask_login import current_user
from sqlalchemy import desc

from app import app, db
from app.models.news import News
from app.service import activity_service, company_service, privacy_service
from app.views.viewmodel.activity import ActivityViewModel
from app.views.viewmodel.jobs import JobsViewModel
from app.views.viewmodel.news import NewsViewModel

blueprint = Blueprint("home", __name__)


@blueprint.route("/", methods=["GET"])
def home():
    jobs = company_service.find_all_jobs(filter_inactive=True)

    random.seed(date.today())
    indices = [i for i in range(len(jobs))]
    random.shuffle(indices)
    jobs_view_models = [JobsViewModel(jobs[i]) for i in indices[:4]]

    activities = activity_service.get_activities_ending_after_now()

    activity_view_models = [ActivityViewModel(a, current_user) for a in activities[:4]]

    news: List[News] = (
        db.session.query(News)
        .filter(
            News.publish_date <= date.today(),
            db.or_(current_user.has_paid, db.not_(News.needs_paid)),
        )
        .order_by(desc(News.publish_date), desc(News.id))
        .limit(8)
        .all()
    )

    news_view_models = [NewsViewModel(n) for n in news]

    return render_template(
        "home/home.htm",
        activities=activity_view_models,
        title="Homepage",
        news=news_view_models,
        jobs=jobs_view_models,
    )


@blueprint.route("/privacy/policy/<any(nl,en):lang>/")
def privacy_policy(lang: Literal["en", "nl"]):
    policies = privacy_service.find_policies()
    if lang == "en":
        return redirect(policies.url_en)
    if lang == "nl":
        return redirect(policies.url_nl)


rule_parser = re.compile(r"<(.+?)>")
splitter = re.compile(r"<.+?>")


@blueprint.route("/jsglue.js")
def serve_js():
    """
    Based on https://github.com/stewartpark/Flask-JSGlue

    The code is inlined, because the pypi is not up-to-date and using the git version
    results in unknown template directories. This may be fixed after a new version
    is published and installable to site-package.
    """
    output = []
    for r in app.url_map.iter_rules():
        endpoint = r.endpoint
        if app.config["APPLICATION_ROOT"] == "/" or not app.config["APPLICATION_ROOT"]:
            rule = r.rule
        else:
            rule = "{root}{rule}".format(
                root=app.config["APPLICATION_ROOT"], rule=r.rule
            )
        rule_args = [x.split(":")[-1] for x in rule_parser.findall(rule)]
        rule_tr = splitter.split(rule)
        output.append((endpoint, rule_tr, rule_args))

    rules = sorted(output, key=lambda x: len(x[1]), reverse=True)

    return make_response(
        render_template("js_bridge.js", namespace="Flask", rules=json.dumps(rules)),
        200,
        {"Content-Type": "text/javascript"},
    )

app/views/news.py
from datetime import date

from flask import Blueprint, Response, abort, render_template
from flask_babel import lazy_gettext as _
from flask_login import current_user

from app import db
from app.decorators import require_role
from app.models.news import News
from app.roles import Roles
from app.service import news_service, role_service
from app.views.viewmodel.news import NewsViewModel

blueprint = Blueprint("news", __name__, url_prefix="/news")


# TODO Move page_nr to query parameter
# TODO https://gitlab.com/studieverenigingvia/viaduct/-/issues/872
@blueprint.route("/", methods=["GET"])
@blueprint.route("/<int:page_nr>/", methods=["GET"])
def root(page_nr=1):
    news_paginator = news_service.get_paginated_news(
        only_published=True, user=current_user, page=page_nr
    )

    news_items = [NewsViewModel(n) for n in news_paginator.items]

    can_write = role_service.user_has_role(current_user, Roles.NEWS_WRITE)
    return render_template(
        "news/list.htm",
        paginator=news_paginator,
        news_items=news_items,
        can_write=can_write,
    )


@blueprint.route("/create/", methods=["GET"])
@blueprint.route("/<news:news>/edit/", methods=["GET"])
@require_role(Roles.NEWS_WRITE)
def edit(news: News = None):
    if news:
        title = _("Edit news")
    else:
        title = _("Create news")
    return render_template("vue_content.htm", title=title)


@blueprint.route("/<news:news>/view/", methods=["GET"])
def view(news: News):
    if not news.can_read():
        return abort(403)

    can_write = role_service.user_has_role(current_user, Roles.NEWS_WRITE)

    return render_template("news/view_single.htm", news=news, can_write=can_write)


@blueprint.route("/rss/", methods=["GET"])
@blueprint.route("/rss/<string:locale>/")
def rss(locale="en"):
    title = "via nieuws" if locale == "nl" else "via news"
    items = (
        db.session.query(News)
        .filter(News.publish_date <= date.today(), db.or_(db.not_(News.needs_paid)))
        .order_by(News.publish_date.desc())
        .limit(20)
    )
    rv = render_template("news/rss.xml", title=title, news_items=items, locale=locale)
    return Response(rv, mimetype="application/atom+xml")

app/templates/news/list.htm
{% extends "content.htm" %}

{% from 'macros/pagination.htm' import render_pagination %}

{% block title -%}
    {{ _('News') }}
{%- endblock title %}

{% block page %}
    <div class="row">
        <div class="col-6">
            <a-breadcrumb v-cloak>
                <a-breadcrumb-item>
                    <a href="{{ url_for("home.home") }}">{{ _('Home') }}</a>
                </a-breadcrumb-item>
                <a-breadcrumb-item>
                    <a href="{{ url_for("news.root") }}">{{ _('News') }}</a>
                </a-breadcrumb-item>
            </a-breadcrumb>
        </div>
        <div class="col-6">
            <div class="btn-group float-right">
                {% if can_write %}
                    <a href="{{ url_for('news.edit') }}" class="btn btn-success">
                        {{ _('Create news item') }}
                    </a>
                {% endif %}

                <a href="{{ url_for('news.rss', locale=get_locale()) }}"
                   class="btn btn-light">
                    {{ _('RSS feed') }}
                </a>
            </div>
        </div>
    </div>
    <hr/>

    {% for item in news_items %}
        <article>
            <div class="row">
                <div class="col-md-8 title">
                    <a href="{{ url_for('news.view', news=item) }}">
                        <h3>{{ item.title }}</h3>
                    </a>
                    <div class="user">
                        <img class="avatar" alt="{{ item.user_name }}"
                             src="{{ item.user_avatar }}">
                        <div class="meta">
                            <span class="author">{{ item.user_name }}</span>
                            <span class="date">{{ item.publish_date}}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {{ item.content
                           | markdown_summary(300,
                                              truncate_method="paragraph",
                                              read_more=item.read_more) }}
                </div>
            </div>
        </article>
    {% endfor %}
    <hr />
    {{ render_pagination(paginator, 'news.root') }}
{% endblock %}

app/templates/news/view_single.htm
{% extends 'content.htm' %}

{% block title -%}
    {{ news.title }} - {{ _('News') }}
{%- endblock title %}

{% block page %}
    <a-breadcrumb v-cloak>
        <a-breadcrumb-item>
            <a href="{{ url_for("home.home") }}">{{ _('Home') }}</a>
        </a-breadcrumb-item>
        <a-breadcrumb-item>
            <a href="{{ url_for("news.root") }}">{{ _('News') }}</a>
        </a-breadcrumb-item>
        <a-breadcrumb-item>
            <a href="{{ url_for('news.view', news=news) }}">{{ news.title }}</a>
        </a-breadcrumb-item>
    </a-breadcrumb>
    <div class='row'>
        <div class='col-md-9 col-md-offset-1'>
            <div class='pb-2 mt-4 mb-2 border-bottom'>
                {% if can_write %}
                    <div class='btn-group float-right'>
                        <a class='btn btn-warning btn-sm' href='
                            {{ url_for('news.edit', news=news) }}'>
                            <i class='far fa-edit'></i> {{ _('Edit news item') }}
                        </a>
                    </div>
                {% endif %}

                <h1>{{ news.title }}</h1>
            </div>

            <div class='row'>
                <div class='col-md-6'>
                    {{_('Written by')}}: <em>{{ news.user.name }}</em>
                </div>
                {% if news.modified_after_creation %}
                    <div class='col-md-6'>
                        {{_('Last modified')}}: <em>{{ news.modified | datetime }} </em><br />
                    </div>
                {% endif %}
                <div class='col-md-6'>
                    {{_('Published at')}}: <em>{{ news.publish_date | date }}</em>
                </div>
            </div>
            <hr>
            <div class='row'>
                <div class='col-md-12 content'>{{ news.content | markdown }}</div>
            </div>
        </div>
    </div>
{% endblock %}