app/models/redirect.py
from sqlalchemy import Column, String

from app.extensions import mapper_registry
from app.models.base_model import BaseEntity


@mapper_registry.mapped
class Redirect(BaseEntity):
    __tablename__ = "redirect"

    fro: str = Column(String(200), unique=True, nullable=False)
    to: str = Column(String(200), nullable=False)

app/views/alv.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_babel import gettext as _
from flask_login import current_user

from app.decorators import require_membership, require_role
from app.exceptions.base import BusinessRuleException
from app.models.alv_model import Alv
from app.roles import Roles
from app.service import alv_service
from app.views.file import send_file_inline

blueprint = Blueprint("alv", __name__, url_prefix="/alv")


@blueprint.route("/", methods=["GET"])
@require_membership
def root():
    return render_template("vue_content.htm", title=_("ALV"))


@blueprint.route("/<alv:alv>/", methods=["GET"])
@require_membership
def view(alv):
    if current_user.locale == "nl":
        title = alv.nl_name
    else:
        title = alv.en_name

    return render_template("vue_content.htm", title=title)


@blueprint.route("/documents/<int:alv_document_id>/<int:version>/", methods=["GET"])
@blueprint.route(
    "/<alv:_alv>/documents/<int:alv_document_id>/<int:version>/", methods=["GET"]
)
@require_membership
def view_document_version(alv_document_id, version, _alv=None):
    if version <= 0:
        return abort(404)

    alv_document = alv_service.get_alv_document_by_id(
        alv_document_id, include_versions=True
    )

    version_idx = version - 1
    if version_idx >= len(alv_document.versions):
        return abort(404)

    alv_document_version = alv_document.versions[version_idx]
    _file = alv_service.get_alv_document_version_file(alv_document_version)

    fn = alv_service.get_alv_document_version_filename(alv_document, version, _file)

    return send_file_inline(_file, filename=fn)


@blueprint.route("/documents/<int:alv_document_id>/", methods=["GET"])
@blueprint.route("/<alv:_alv>/documents/<int:alv_document_id>/", methods=["GET"])
@require_membership
def view_document_version_latest(alv_document_id, _alv=None):
    alv_document = alv_service.get_alv_document_by_id(
        alv_document_id, include_versions=True
    )

    version_idx = len(alv_document.versions) - 1

    alv_document_version = alv_document.versions[version_idx]
    _file = alv_service.get_alv_document_version_file(alv_document_version)

    fn = alv_service.get_alv_document_version_filename(alv_document, version_idx, _file)

    return send_file_inline(_file, filename=fn)


@blueprint.route("/<alv:alv>/document/minutes/")
@require_membership
def view_minutes(alv: Alv):
    _file = alv_service.get_alv_minutes_file(alv)
    fn = alv_service.get_alv_minutes_filename(alv, _file)

    return send_file_inline(_file, fn)


@blueprint.route("/create/", methods=["GET", "POST"])
@blueprint.route("/<alv:alv>/edit/<string:__>/", methods=["GET", "POST"])
@blueprint.route("/<alv:alv>/edit/", methods=["GET", "POST"])
@require_role(Roles.ALV_WRITE)
def create_edit(alv=None, __=None):
    if alv:
        title = _("Edit") + " ALV"
    else:
        title = _("Create") + " ALV"
    return render_template("vue_content.htm", title=title)


@blueprint.route("/<alv:alv>/remove/", methods=["POST"])
@require_role(Roles.ALV_WRITE)
def delete(alv: Alv):
    try:
        alv_service.delete_alv(alv)
    except BusinessRuleException:
        flash(_("Cannot delete %s, as it has documents attached.") % alv.name, "danger")
        return redirect(url_for("alv.view", alv=alv))

    return redirect(url_for("alv.root"))

app/views/home.py
import json
import random
import re
from datetime import date
from typing import List, Literal

from flask import Blueprint, make_response, redirect, render_template
from flask_login import current_user
from sqlalchemy import desc

from app import app, db
from app.models.news import News
from app.service import activity_service, company_service, privacy_service
from app.views.viewmodel.activity import ActivityViewModel
from app.views.viewmodel.jobs import JobsViewModel
from app.views.viewmodel.news import NewsViewModel

blueprint = Blueprint("home", __name__)


@blueprint.route("/", methods=["GET"])
def home():
    jobs = company_service.find_all_jobs(filter_inactive=True)

    random.seed(date.today())
    indices = [i for i in range(len(jobs))]
    random.shuffle(indices)
    jobs_view_models = [JobsViewModel(jobs[i]) for i in indices[:4]]

    activities = activity_service.get_activities_ending_after_now()

    activity_view_models = [ActivityViewModel(a, current_user) for a in activities[:4]]

    news: List[News] = (
        db.session.query(News)
        .filter(
            News.publish_date <= date.today(),
            db.or_(current_user.has_paid, db.not_(News.needs_paid)),
        )
        .order_by(desc(News.publish_date), desc(News.id))
        .limit(8)
        .all()
    )

    news_view_models = [NewsViewModel(n) for n in news]

    return render_template(
        "home/home.htm",
        activities=activity_view_models,
        title="Homepage",
        news=news_view_models,
        jobs=jobs_view_models,
    )


@blueprint.route("/privacy/policy/<any(nl,en):lang>/")
def privacy_policy(lang: Literal["en", "nl"]):
    policies = privacy_service.find_policies()
    if lang == "en":
        return redirect(policies.url_en)
    if lang == "nl":
        return redirect(policies.url_nl)


rule_parser = re.compile(r"<(.+?)>")
splitter = re.compile(r"<.+?>")


@blueprint.route("/jsglue.js")
def serve_js():
    """
    Based on https://github.com/stewartpark/Flask-JSGlue

    The code is inlined, because the pypi is not up-to-date and using the git version
    results in unknown template directories. This may be fixed after a new version
    is published and installable to site-package.
    """
    output = []
    for r in app.url_map.iter_rules():
        endpoint = r.endpoint
        if app.config["APPLICATION_ROOT"] == "/" or not app.config["APPLICATION_ROOT"]:
            rule = r.rule
        else:
            rule = "{root}{rule}".format(
                root=app.config["APPLICATION_ROOT"], rule=r.rule
            )
        rule_args = [x.split(":")[-1] for x in rule_parser.findall(rule)]
        rule_tr = splitter.split(rule)
        output.append((endpoint, rule_tr, rule_args))

    rules = sorted(output, key=lambda x: len(x[1]), reverse=True)

    return make_response(
        render_template("js_bridge.js", namespace="Flask", rules=json.dumps(rules)),
        200,
        {"Content-Type": "text/javascript"},
    )

app/views/redirect.py
from flask import Blueprint, render_template
from flask_babel import gettext

from app.decorators import require_role
from app.roles import Roles

blueprint = Blueprint("redirect", __name__, url_prefix="/redirect")


@blueprint.route("/", methods=["GET"])
@require_role(Roles.REDIRECT_WRITE)
def view():
    return render_template("vue_content.htm", title=gettext("Redirects"))

app/templates/base.htm
{%- from "macros/flash.htm" import render_flash -%}
{%- from "macros/base.htm" import render_membership_confirmation_pending_message, render_banner -%}

<!DOCTYPE html>
<html lang="{{ locale }}" prefix="og: http://ogp.me/ns#">
    <head>
        {% set seo_fields = get_seo_fields(locale) %}
        {% set title_s %}{%- block title -%}{% endblock %} - via{% endset %}
        <title>{{ title_s }}</title>

        <meta name="description" content="{{seo_fields.description}}" />
        <meta name="keywords" content="{{seo_fields.tags}}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta property="og:title" content="{{ title_s }}" />
        <meta property="og:description" content="{{seo_fields.description}}" />
        <meta property="og:url" content="{{ request_url }}" />
        <meta property="og:type" content="website" />
        <meta property="og:locale" content="{{ get_locale() }}_NL"/>

        {% block og_image %}
            <meta property="og:image" content="{{ request_url_root }}static/img/via_facebook_thumbnail.png" />
            <meta property="og:image:alt" content="via logo" />
            <meta property="og:image:type" content="image/png" />
            <meta property="og:image:width" content="1200" />
            <meta property="og:image:height" content="630" />
        {% endblock %}

        <!-- <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon"> -->
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico', v='gAdm72Y3wv') }}">
        <link rel="mask-icon" href="{{ url_for('static', filename='img/safari-pinned-tab.svg', v='gAdm72Y3wv') }}" color="#5bbad5">
        <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/apple-touch-icon.png', v='gAdm72Y3wv') }}">
        <link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='img/favicon-192x192.png', v='gAdm72Y3wv') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png', v='gAdm72Y3wv') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png', v='gAdm72Y3wv') }}">
        <link rel="manifest" href="{{ url_for('static', filename='img/site.webmanifest', v='gAdm72Y3wv') }}">
        <meta name="msapplication-TileColor" content="#2d89ef">
        <meta name="msapplication-config" content="{{ url_for('static', filename='img/browserconfig.xml', v='gAdm72Y3wv') }}">
        <meta name="theme-color" content="#ffffff">

        <link href="{{static_url(url_for('static', filename='styles.css')) }}" rel="stylesheet" />

        {% if not app_config['DEBUG'] %}
            <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-PKHM7J9');</script>
        {% endif %}

        <script>
            window.viaduct = {};
            window.viaduct.locale = "{{get_locale()}}";
            SentryConfig = {
                dsn: "{{ app_config['SENTRY_DSN_FRONTEND'] }}",
                release: "{{ app_version }}",
                environment: "{{ app_config['ENVIRONMENT'] }}",
            }
        </script>
        <script src="{{static_url(url_for('home.serve_js'))}}"></script>

        {% block includes %}
        {% endblock %}

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    </head>

    <body>
        {%- if not (__fullscreen_mode is defined and __fullscreen_mode) -%}
            {% include 'navigation/view_bar.htm' %}

            {% if membership_view.membership_confirmation_pending %}
                {{ render_membership_confirmation_pending_message(current_user) }}
            {% endif %}

            {% if banner_view.show_banner %}
                {{ render_banner(banner_view) }}
            {% endif %}

        {%- endif -%}
        {% block below_menu %}
        {% endblock %}

        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PKHM7J9"
                          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

        <div class="container" id="container-main">
            <div class="row">
                <div class="col-sm-12" id="messages">
                    {{ render_flash() }}
                </div>
            </div>

            {% block page %}
            {% endblock %}

            <hr>
            <footer-carousel></footer-carousel>
        </div>

        {%- if not (__fullscreen_mode is defined and __fullscreen_mode) -%}
            {% include 'page/get_footer.htm' %}
        {%- endif -%}

        <script src="{{ static_url(url_for('static', filename='main.js')) }}"></script>
        {% block post_main_include %}
        {% endblock %}
    </body>
</html>

app/templates/content.htm
{% extends "base.htm" %}

{% block page %}
<div class="row">
    {% include 'navigation/view_sidebar.htm' %}

    <div class="col-md-10">
        {% include 'navigation/view_backtrack.htm' %}

        {% block content %}{% endblock %}
    </div>
</div>
{% endblock %}

app/templates/redirect.htm
{% extends 'content.htm' %}

{% from 'macros/form.htm' import render_form %}
{% block title %}{{ _('Redirects') }}{% endblock %}
{% block content %}

<h1>Omleiding</h1>
<p>Creëer omleidingen van URLs, naar URLs.</p>

<h2>{% if redirection %}Bewerk{% else %}Nieuwe{% endif %} omleiding</h2>

{{ render_form(form, form_class='form-inline') }}

{% if redirection %}
    <a href="{{ url_for('redirect.view') }}" class='btn btn-success'>Nieuw</a>
{% endif %}

<h2>Bestaande omleidingen</h2>
<table class='table table-responsive'>
    <thead>
    <tr>
        <th>Aanpassen</th>
        <th>Verwijderen</th>
        <th>Van</th>
        <th>Naar</th>
    </tr>
    </thead>

    <tbody>
        {% for r in redirections %}
            <tr>

                <td>
                    <a href="{{ url_for('redirect.view', redirection=r) }}"
                       class='btn btn-secondary btn-sm'>
                        <i class='far fa-edit'></i>
                    </a>
                </td>
                <td>
                    <form action="{{ url_for('redirect.delete', redirection=r )}}"
                          method="post" class="form-inline">
                        {{ form.csrf_token() }}
                        <button class='btn btn-danger btn-sm' type="submit">
                            <i class='fas fa-trash'></i>
                        </button>
                    </form>

                </td>
                <td>{{ r.fro }}</td>
                <td>{{ r.to }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

app/templates/vue_content.htm
{% extends "content.htm" %}
{% from "macros/vue.htm" import render_vue_app %}

{% block title %}{{ title }}{% endblock %}

{% block page %}
    {{ render_vue_app(keep_alive_include, locale) }}
{% endblock %}